name: Remote Deploy Staging to GitHub Pages

on:
  push:
    branches:
      - staging
    repository_dispatch:

jobs:
  # Run playwright e2e tests first:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install subversion
        run: sudo apt-get update && sudo apt-get install -y screen subversion
      - name: Fetch test data from subversion
        run: svn checkout https://svn.vsp.tu-berlin.de/repos/public-svn/shared/simwrapper-testdata
      - name: Run fileserver in background screen
        # run: screen -dmS httpserver python -m http.server 8000 --directory simwrapper-testdata && sleep 4
        run: |
          docker run -d --name http-server -p 8000:8000 \
            -v ${{ github.workspace}}/simwrapper-testdata:/usr/share/nginx/html:ro \
            nginx:alpine
      - name: Verify file server is running
        run: |
          sleep 5
          curl -f http://localhost:8000
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: stop file server
        if: always()
        #run: screen -S httpserver -X quit || true
        run: docker stop http-server && docker rm http-server || true

  # Ping staging build -IF- tests passed
  notify-staging:
    needs: e2e-tests
    runs-on: ubuntu-latest
    steps:
      - name: PING staging
        if: github.event.action != 'pong'
        run: |
          curl -X POST https://api.github.com/repos/simwrapper/staging/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.BUILD_STAGING }} \
          --data '{"event_type": "ping", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
